apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coffee-shop-postgresql.fullname" . }}
  labels:
    app.kubernetes.io/component: postgresql-persistent
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/part-of: {{ .Values.openshiftApplicationName }}
    {{- include "coffee-shop-postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coffee-shop-postgresql.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coffee-shop-postgresql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coffee-shop-postgresql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        envFrom:
        - secretRef:
            name: {{ include "coffee-shop-postgresql.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: {{ .Values.service.name }}
            containerPort: {{ .Values.service.port }}
            protocol: {{ .Values.service.protocol }}
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: coffee-shop-postgresql-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: coffee-shop-postgresql-data
        persistentVolumeClaim:
          claimName: {{ include "coffee-shop-postgresql.fullname" . }}
