apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffee-shop-postgresql.fullname" . }}
  labels:
    {{- include "coffee-shop-postgresql.labels" . | nindent 4 }}
stringData:
  POSTGRESQL_DATABASE: {{ required "credentials.database is required" .Values.credentials.database }}
  POSTGRESQL_USER: {{ required "credentials.username is required" .Values.credentials.username }}
  POSTGRESQL_PASSWORD: {{ required "credentials.password is required" .Values.credentials.password }}
type: Opaque
