---
- debug:
    msg: "LAB 01 ENVIRONMENT SETUP (LINUX)"

- name: install python requirements
  become: true
  ansible.builtin.pip:
    name:
      - kubernetes

- name: install kubectl krew
  ansible.builtin.shell: |-
    (
      set -x; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
    )

- name: set up the path to include the location of the plug-ins
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="${KREW_ROOT:-${HOME}/.krew}/bin:$PATH"'

- name: create symlink /usr/local/bin/kubectl-krew
  become: true
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.krew/bin/kubectl-krew"
    path: /usr/local/bin/kubectl-krew
    state: link

- name: install kubectl krew neat
  ansible.builtin.shell: |-
    kubectl krew install neat

- name: create symlink /usr/local/bin/kubectl-neat
  become: true
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.krew/bin/kubectl-neat"
    path: /usr/local/bin/kubectl-neat
    state: link

- debug:
    msg: "LAB 01 ENVIRONMENT SETUP (LINUX) - COMPLETED"
